### ISSUE TITLE
external link icon appearing for some internal links?

### ISSUE THREAD

**Issue by charlottesales** [kentcc/kelsi#39]
Hi, 

The external link icon is showing from some internal links. Look at http://www.kent.gov.uk/_kelsi-beta/news-and-events/patricks-message and you can see it appearing for each message.

**Comment by LidorLapid** [comment]
Hiya. The external links icons are showing in this case because the website is being viewed on the kent.gov.uk domain, and the links are all pointing to kent.gov.uk as a result (and are therefore treated as 'external'). Please see beta.kelsi.org.uk/news-and-events/patricks-message -- things should be looking better over there!
