### ISSUE TITLE
Additional 'Edit contents'

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#56]
Is it possible to have an Edit contents field appear 1) on the landing pages 2) on the Settings pages, underneath the blue heading. Thanks

**Comment by LidorLapid** [comment]
As discussed, I've implemented this in the form of an additional metadata field so that it can be limited to two lines. On landing pages, the metadata field is called landing.page.intro, and on persona pages, it's called persona.page.intro. In both cases there is a requirement that the relevant metadata schema and paint layout are applied -- this sounds obvious, but I've noticed some landing pages use an incorrect paint layout ('Default') and don't have the landing page metadata schema applied.
